### ISSUE TITLE
Refactor and namespace

### ISSUE THREAD

**Issue by stephencroberts** [contentful/contentful-importer.rb#12]
Would you consider refactoring the code and using namespaces? Currently, there are several files under lib which could cause `require` issues or conflicts. It'd be great to see a more standardized ruby gem file structure and namespacing. I'd be happy to draft a version and do a pull request if you're open to it. Thanks!

**Comment by pxlpnk** [comment]
@stephencroberts What files are you talking about in detail? Yes please draft a PR, a better namespacing would make sense. something like `Contentful::Importer`

**Comment by stephencroberts** [comment]
@pxlpnk Sorry I've been super busy launching a website on Contentful. :) 

All of the ones in the lib folder seem to be candidates for conflicts, particularly `cli` and `configuration` since those are pretty general names. To include those in other scripts or gems, I have to simply `require cli` or `require configuration` rather than something like `require contentful/cli`. I should have some time in the next week or so to draft something up. 

I've also been working on a few gems for contentful including a generic csv importer, sitecore exporter/importer, algolia search updater, and cloudsearch updater.

**Comment by neonichu** [comment]
@stephencroberts thanks for offering to contribute, we have actually added namespaces in #14 and will release a new version of the gem including this soon.

**Comment by stephencroberts** [comment]
Awesome, thanks guys.
