### ISSUE TITLE
Error when running import

### ISSUE THREAD

**Issue by amalfra** [contentful/contentful-importer.rb#13]
I am getting following error when running the importer. 
undefined method `entries' for #<Contentful::Management::Unauthorized:0x007f6180067be0>

Any idea?

**Comment by amalfra** [comment]
Is that something with ACESS_TOKEN?

**Comment by pxlpnk** [comment]
Yes you need to create an access token as described in the readme and put it in your settings file.

**Comment by amalfra** [comment]
Yes, i have the access token put in access_token key of settings.yml

**Comment by amalfra** [comment]
Any help? This error when i use access token from here: https://www.contentful.com/developers/documentation/content-management-api/#getting-started

undefined method `entries' for #<Contentful::Management::NotFound:0x007fb428034768>

**Comment by pxlpnk** [comment]
Did you set the space and organization id in your settings.yml file? 
Could you please send your file to support@contentful.com. Please make sure to obfuscate your access token in the file.

**Comment by amalfra** [comment]
@pxlpnk Done.

**Comment by neonichu** [comment]
The original issue has been solved, content types haven't been imported using `--import-content-types`.
