### ISSUE TITLE
import error no implicit conversion of false into Hash

### ISSUE THREAD

**Issue by dasblitz** [contentful/contentful-importer.rb#30]
I've managed to succesfully export a product table from mysql using the export-database gem. Meaning I got no errors and I now have a json file for each row in my table). When I try to run the  import gem I receive the following error:

```
contentful-importer --configuration=import-settings.yml test-credentials
/usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/command.rb:65:in `merge!': no implicit conversion of false into Hash (TypeError)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/command.rb:65:in `initialize'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:334:in `new'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:334:in `parse'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:330:in `parse'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:308:in `run'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/bin/contentful-importer:12:in `<top (required)>'
       	from /usr/local/bin/contentful-importer:23:in `load'
       	from /usr/local/bin/contentful-importer:23:in `<main>'
```

I have no experience with Ruby so any help in which direction I should be looking to solve this would be highly appreciated :)

**Comment by dlitvakb** [comment]
Hey @dasblitz,

Could you share your `import-settings.yml` file, with the credentials removed?

Cheers

**Comment by dasblitz** [comment]
Hi @dlitvakb 

Yes added below :)

```
#PATH to all data
data_dir: import_data

#JSON describing your content model
content_model_json: contentful_model.json

#Contentful credentials
access_token: 
organization_id: 
space_id: 
default_locale: en-US
```

**Comment by dlitvakb** [comment]
Hey @dasblitz,

Looks like the YAML parser is not being able to properly parse your file.

Please try prepending `---` as the first line of your file (3 hiphens), then try again.

Please let me know if that helps.

Cheers

**Comment by dasblitz** [comment]
Tnx for the quick reply,

this seems to get me a little further but now this is the error I'm getting:

```
contentful-importer --configuration=settings.yml import-entries
I, [2016-09-07T11:09:37.315241 #54826]  INFO -- : Processing collection: product
I, [2016-09-07T11:09:37.370802 #54826]  INFO -- : Creating entry: product_10.
W, [2016-09-07T11:09:37.371036 #54826]  WARN -- : Using in memory store
/usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/parallel_importer.rb:221:in `import_entry': undefined method `entries' for #<Contentful::Management::Unauthorized:0x007febe1ce1060> (NoMethodError)
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/parallel_importer.rb:71:in `block in import_entries'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/parallel_importer.rb:68:in `glob'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/parallel_importer.rb:68:in `import_entries'
       	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/parallel_importer.rb:56:in `block (2 levels) in import_in_threads'
```

**Comment by dlitvakb** [comment]
Ok, this looks like a permissions issue.

Make sure to have your Management token in your settings file. You can fetch it [here](https://www.contentful.com/developers/docs/references/authentication/#getting-an-oauth-token)

Hope this helps

**Comment by dasblitz** [comment]
Ok I found the test-credentials command. On that page I'm using the OAuth token that I see under the section Getting an OAuth token.... logged in as ... here's your OAuth token:

Is this the one I should be using, or do I need to follow the steps under:

Creating an OAuth 2.0 application

**Comment by dlitvakb** [comment]
That's the one, the one that already appears there.

**Comment by dasblitz** [comment]
ok I was already using that one, I'm quite sure I have the right credentials then. Need to work on a different project today, but I will look into it again tonight :)

**Comment by dasblitz** [comment]
My bad, I referred to the wrong yaml file in the cli after I prepended ```---```. The import now succeeded. Many thanks for your patience, please don't punch me ;)

**Comment by dlitvakb** [comment]
Haha! No problem!! Cheers
